# -*- coding: utf-8 -*-
"""Reproducible_Battery_Thermal_Runaway.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXFeAl4LKNc5g1uMUyUgaCJPGTfzSDm2

# Visualization for the manuscripts: Data-driven early detection of thermal runaway in lithium-ion batteries⋆, Shubha Banerjee, H.Ruan et.al

### Loading the datasets from the Github Repo and unzip,  The datasets can be loaded from:
https://github.com/shubha3/pTRpred/tree/main/Reproducible_Plots
"""

!pip install adjustText

#Specify and Create the Required Directories
import os
if not os.path.exists('NREL_Plots'):
    os.mkdir('NREL_Plots')
if not os.path.exists('NREL_Plots_SVD'):
    os.mkdir('NREL_Plots_SVD')
if not os.path.exists('Simulated_Datasets_Plots'):
    os.mkdir('Simulated_Datasets_Plots')
if not os.path.exists('T_Results'):
    os.mkdir('T_Results')
if not os.path.exists('NREL_Dataset'):
    os.mkdir("NREL_Dataset")
if not os.path.exists('Simulated_Datasets'):
    os.mkdir('Simulated_Datasets')
if not os.path.exists("NREL_Data_Results_SVD"):
    os.mkdir('NREL_Data_Results_SVD')
if not os.path.exists("Threshold_Sensitivity"):
    os.mkdir("Threshold_Sensitivity")

from google.colab import userdata
token = userdata.get("GITHUB_TOKEN")

url = "https://raw.githubusercontent.com/shubha3/pTRpred/main/Reproducible_Plots/SVD_result.zip"

!curl -L \
  -H "Authorization: token {token}" \
  -H "Accept: application/vnd.github.raw" \
  "{url}" \
  -o "SVD_result.zip"
!unzip -o SVD_result.zip -d SVD_result

from google.colab import userdata
token = userdata.get("GITHUB_TOKEN")

url = "https://raw.githubusercontent.com/shubha3/pTRpred/main/Reproducible_Plots/Simulated_Datasets.zip"

!curl -L \
  -H "Authorization: token {token}" \
  -H "Accept: application/vnd.github.raw" \
  "{url}" \
  -o "Simulated_Datasets.zip"
!unzip -o Simulated_Datasets.zip -d Simulated_Datasets

token = userdata.get("GITHUB_TOKEN")

url = "https://raw.githubusercontent.com/shubha3/pTRpred/main/Reproducible_Plots/T_Results.zip"

!curl -L \
  -H "Authorization: token {token}" \
  -H "Accept: application/vnd.github.raw" \
  "{url}" \
  -o "T_Results.zip"
!unzip -o T_Results.zip -d T_Results

token = userdata.get("GITHUB_TOKEN")

url = "https://raw.githubusercontent.com/shubha3/pTRpred/main/Reproducible_Plots/NREL_Dataset.zip"

!curl -L \
  -H "Authorization: token {token}" \
  -H "Accept: application/vnd.github.raw" \
  "{url}" \
  -o "NREL_Dataset.zip"
!unzip -o NREL_Dataset.zip -d NREL_Dataset

rm -rf SVD_result/__MACOSX/*

rm -rf NREL_Dataset/__MACOSX/*

rm -rf Simulated_Datasets/__MACOSX/*

rm -rf T_Results_Whole/__MACOSX/*

rm -rf SVD_result/__MACOSX/*

os.remove("NREL_Dataset.zip")
os.remove("SVD_result.zip")
os.remove("Simulated_Datasets.zip")
os.remove("T_Results.zip")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
import os
from matplotlib.colors import TwoSlopeNorm
from numpy import trapezoid
from math import factorial
from itertools import chain, combinations
import importlib.util
from matplotlib.lines import Line2D
import re
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

#Apply the standard style configs for all of the plots:
def apply_standard_style():
    """The plots configs"""
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans"],
        "axes.titlesize": 21,
        "axes.labelsize": 18,
        "xtick.labelsize": 18,
        "ytick.labelsize": 18,
        "legend.fontsize": 18,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "savefig.dpi": 300,
        "figure.constrained_layout.use": True,
        "figure.facecolor": 'white',
        'axes.facecolor': 'white'
    })

import inspect

def plot_battery_sensitivity(csv_path, SVD = True, battery_type_list = ['Lab/Generic', 'Lab/Custom'], window_prefix ='X30', threshold_level = 0.3, output_fig_name = 'Battery_Threshold_Sensitivity.png'):
    df = pd.read_csv(csv_path)
    if df.columns[0].startswith('Unnamed'):
        df = df.iloc[:, 1:]
    df.columns = [c.strip() for c in df.columns]
    value_cols = [c for c in df.columns if c.startswith(window_prefix + '_')]
    label_map = {1: 'Positive', 2: 'Unknown', 0: 'Negative'}
    palette = {'Negative': 'orange', 'Positive': 'darkblue', 'Unknown': 'firebrick'}
    plt.figure()
    if len(battery_type_list) == 4:
        fig, axes = plt.subplots(2, 2, figsize = (14, 18.66), constrained_layout = True)
    else:
        fig, axes = plt.subplots(1, 3, figsize = (18, 8), constrained_layout = True)
    axes_list = axes.flatten()
    for i, battery_type in enumerate(battery_type_list):
        ax = axes_list[i]
        df_sub = df[df['battery_category'] == battery_type].copy()
        df_long = pd.melt(
          df_sub, id_vars = ['Label'],
          value_vars = value_cols,
          var_name = 'threshold',
          value_name = 'real_time_detection_score')
        df_long['window_lower'] = df_long['threshold'].apply(lambda X: int(X.split("_")[0][1:]))
        df_long['window_higher'] = df_long['threshold'].apply(lambda X: int(X.split("_")[1]))
        #Filtering and Transformation
        value_cols = [c for c in df_sub.columns if c.startswith(window_prefix)]
        df_sub['threshold'] = 0.3
        df_long['Label_Text'] = df_long['Label'].map(label_map)
        sns.stripplot(
            data=df_long, x='threshold', y='real_time_detection_score', hue='Label_Text',
            palette=palette, ax=ax, jitter=0.25, size=12, alpha=0.7, legend = False)
        ax.set_ylim(0.1, 1)
        ax.axhline(y=threshold_level, color='brown', linestyle='--', linewidth=2)
        #Setting the Title labels:
        title_suffix = " (SVD Procedure)" if SVD else ""
        ax.set_title(f"{battery_type}{title_suffix}", fontweight='bold', pad=12)
        ax.set_xlabel('Maximal Window Size')
        new_labels = [label.get_text().split('_')[-1] for label in ax.get_xticklabels()]
        ax.set_xticklabels(new_labels)
        ax.set_ylabel('Maximal Detected Value')
        ax.set_ylim(0.05, 1)
        ax.tick_params(axis='x')
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.grid(False)
    #Creating Legend Manually:
    legend_handles = [
        Line2D([0], [0], marker="o", color="w", label="Negative",
               markerfacecolor=palette["Negative"], markeredgecolor="black", markersize=8),
        Line2D([0], [0], marker="o", color="w", label="Positive",
               markerfacecolor=palette["Positive"], markeredgecolor="black", markersize=8),
        Line2D([0], [0], marker="o", color="w", label="Unknown",
               markerfacecolor=palette["Unknown"], markeredgecolor="black", markersize=8),
        Line2D([0], [0], color="#7F2704", linestyle="--", linewidth=2.2,
               label=f"Threshold = {threshold_level}")
    ]
    fig.legend(
        handles=legend_handles,
        loc="lower center",
        ncol=4,
        bbox_to_anchor=(0.5, -0.07),
        frameon=True,
        fancybox=True
    )
    plt.savefig(output_fig_name, bbox_inches='tight')
    plt.show()
    plt.close()
    print(f"Standardized plot saved as: {output_fig_name}")

apply_standard_style()

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/T_Results_Whole.csv', SVD = False, battery_type_list = ['Commercial (LCO)', 'Soteria', 'Soteria (Control)'],
                         window_prefix = 'X10', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_T_X10.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = False, battery_type_list = ['Lab/Generic', 'Lab/Custom', 'Commercial (LFP)', 'Commercial (NMC)'],
                         window_prefix = 'X10', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_T_X10_b2.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/T_Results_Whole.csv', SVD = False, battery_type_list = ['Commercial (LCO)', 'Soteria', 'Soteria (Control)'],
                         window_prefix = 'X30', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_T_X30.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = False, battery_type_list = ['Lab/Generic', 'Lab/Custom', 'Commercial (LFP)', 'Commercial (NMC)'],
                         window_prefix = 'X30', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_T_X30_b2.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/T_Results_Whole.csv', SVD = False, battery_type_list = ['Commercial (LCO)', 'Soteria', 'Soteria (Control)'],
                         window_prefix = 'X40', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_T_X40.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = False, battery_type_list = ['Lab/Generic', 'Lab/Custom', 'Commercial (LFP)', 'Commercial (NMC)'],
                         window_prefix = 'X40', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_T_X40_b2.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = True, battery_type_list = ['Commercial (LCO)', 'Soteria', 'Soteria (Control)'],
                         window_prefix = 'X10', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_SVD_X10.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = True, battery_type_list = ['Lab/Generic', 'Lab/Custom', 'Commercial (LFP)', 'Commercial (NMC)'],
                         window_prefix = 'X10', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_SVD_X10_b2.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = True, battery_type_list = ['Commercial (LCO)', 'Soteria', 'Soteria (Control)'],
                         window_prefix = 'X30', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_SVD_X30.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = True, battery_type_list = ['Lab/Generic', 'Lab/Custom', 'Commercial (LFP)', 'Commercial (NMC)'],
                         window_prefix = 'X30', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_SVD_X30_b2.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = True, battery_type_list = ['Commercial (LCO)', 'Soteria', 'Soteria (Control)'],
                         window_prefix = 'X40', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_SVD_X40.png')

plot_battery_sensitivity('Simulated_Datasets/Simulated_Datasets/battery_cell_SVD_whole_stats.csv', SVD = True, battery_type_list = ['Lab/Generic', 'Lab/Custom', 'Commercial (LFP)', 'Commercial (NMC)'],
                         window_prefix = 'X40', threshold_level = 0.3, output_fig_name = 'Threshold_Sensitivity/Battery_Threshold_Sensitivity_SVD_X40_b2.png')

"""## Drawing the Visualization for the pTRPred on Temperature Dimension:"""

def apply_standard_style():
    """The plots configs"""
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans"],
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 18,
        "ytick.labelsize": 18,
        "legend.fontsize": 18,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "savefig.dpi": 300,
        "figure.constrained_layout.use": True,
        "figure.facecolor": 'white',
        'axes.facecolor': 'white'
    })
apply_standard_style()

def plot_overlay_on_ax(ax, df, title, threshold = 0.3):
    ax2 = ax.twinx()
    l1, _ = ax.plot(df['time_ind'], df['temperature'], color = 'darkblue', lw = 1.5, label = 'Temp')
    ax.set_ylabel('Temperature (°C)', color = 'darkblue')
    ax.tick_params(axis = 'y', labelcolor = 'darkblue')
    #
    l2 = ax2.plot(df['time_ind'], df['detected_value_rt'], color = 'red', lw = 1.5, label = 'Detection')
    ax2.set_ylabel('Real-Time Detected Score', color = 'red')
    ax2.tick_params(axis = 'y', labelcolor = 'red')
    ax2.set_ylim(-0.1, 1.1)
    ax2.axhline(y = threshold, color = 'darkgreen', linestyle = '--', lw = 1.5)
    ax.set_title(title, fontweight = 'bold', pad = 8)
    ax.set_xlabel('Time (0.1s)')
    return [l1, l2]

#Visualize the 2 * 2 plots for the Temperatures
def plot_battery_quad_T(file_list, threshold = 0.3, point_before = 100, point_after = 100,
                      output_name = 'cell1_name_list.png'):
    apply_standard_style()
    fig, axes = plt.subplots(2, 2, figsize = (16, 16))
    axes_flat = axes.flatten()
    for i, filename in enumerate(file_list):
        ax = axes_flat[i]
        df = pd.read_csv(filename)
        trigger_indices = df.index[df['detected_value_rt'] >= threshold].tolist()
        if trigger_indices:
            trigger_point = trigger_indices[0]
            start_idx = max(0, trigger_point - point_before)
            end_idx = min(len(df), trigger_point + point_after)
            df_plot = df.iloc[start_idx:end_idx,:].reset_index(drop = True)
            temp_at_trigger = df.iloc[trigger_point]['temperature']
        else:
            df_plot = df.iloc[:min(len(df), 1500)].reset_index(drop = True)
            temp_at_trigger = None
        #draw the two axis:
        ax_score = ax.twinx()
        line_t,  = ax.plot(df_plot.index, df_plot['temperature'], color = 'darkblue', lw = 2, label = 'Temperature')
        ax.set_ylabel('Temperature (°C)', color = 'darkblue')
        ax.tick_params(axis = 'y', labelcolor = 'darkblue')
        line_d, = ax_score.plot(df_plot.index, df_plot['detected_value_rt'], color = '#d62728', lw = 2, label = 'Detection')
        ax_score.set_ylabel('Real-Time Detected Score', color = '#d62728')
        ax_score.tick_params(axis = 'y', labelcolor = '#d62728')
        ax_score.set_ylim(-0.2, 1.0)
        ax_score.axhline(y = threshold, color = 'green', ls = '--', alpha = 0.6)
        for spine in ax.spines.values():
            spine.set_visible(False)
        for spine in ax_score.spines.values():
            spine.set_visible(False)
        ax.grid(False)
        ax_score.grid(False)
        soc_match = re.search(r'-(\d+)(SOC|SOC)', filename, re.I)
        soc_str = f"{soc_match.group(1)}% SOC" if soc_match else 'Unknown SOC'
        cell_label = os.path.basename(filename).split('-')
        title_text = "Visualization - Temperature vs. Detected Score"
        if temp_at_trigger:
            title_text += f"\n Temperature at Trigger: {temp_at_trigger:.1f} Temperature (°C)"
        ax.set_title(title_text,  fontweight = 'bold', pad = 25)
        ax.set_label('Time Indice (0.1s)')
        legend_handles = [line_t, line_d]
    fig.legend(legend_handles, ['Temperature (°C)', 'Real-time Detection Score'],
               loc='lower center', ncol=2, bbox_to_anchor=(0.5, 0.02), frameon=True, edgecolor='black')
    #Tight Layout in the Bottom here:
    plt.tight_layout(rect=[0, 0.06, 1, 0.95])
    plt.savefig(output_name, bbox_inches='tight', dpi = 300)

rm -rf SVD_result/__MACOSX/*

folder_path = 'T_Results/T_Results'
valid_extensions = ('.csv')
if not os.path.exists("NREL_Plots"):
    os.mkdir("NREL_Plots")
step_size = 4
list_files = os.listdir(folder_path)
for i in range(0, len(list_files), step_size):
    file_list = list_files[i:(i + step_size)]
    file_list = [folder_path + "/" + file for file in file_list if file != "__MACOSX"]
    plot_battery_quad_T(file_list, threshold = 0.3, point_before = 100, point_after = 100,
                      output_name = f'NREL_Plots/cell{i}_cell{i+step_size}_T_result_visualization_NREL.png')

def apply_standard_style():
    """The plots configs"""
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans"],
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 18,
        "ytick.labelsize": 18,
        "legend.fontsize": 18,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "savefig.dpi": 300,
        "figure.constrained_layout.use": True,
        "figure.facecolor": 'white',
        'axes.facecolor': 'white'
    })
apply_standard_style()
#Visualize the 2 * 2 plots for the SVD Procedure
def plot_battery_quad_SVD(file_list, threshold = 0.3, point_before = 100, point_after = 100,
                      output_name = 'cell1_name_list.png'):
    apply_standard_style()
    fig, axes = plt.subplots(2, 2, figsize = (16, 16))
    axes_flat = axes.flatten()
    for i, filename in enumerate(file_list):
        ax = axes_flat[i]
        df = pd.read_csv(filename)
        trigger_indices = df.index[df['detected_value_rt'] >= threshold].tolist()
        if trigger_indices:
            trigger_point = trigger_indices[0]
            start_idx = max(0, trigger_point - point_before)
            end_idx = min(len(df), trigger_point + point_after)
            df_plot = df.iloc[start_idx:end_idx,:].reset_index(drop = True)
            temp_at_trigger = df.iloc[trigger_point]['signal']
        else:
            df_plot = df.iloc[:min(len(df), 1500)].reset_index(drop = True)
            temp_at_trigger = None
        #draw the two axis:
        ax_score = ax.twinx()
        #Left Column(Blue):
        line_t, = ax.plot(df_plot.index, df_plot['signal'], color='darkblue', lw=2, label='First Singular Value')
        ax.set_ylabel('Signal(First Singular Value)', color = 'darkblue')
        ax.tick_params(axis = 'y', labelcolor = 'darkblue')
        #Right Column(Red):
        line_d, = ax_score.plot(df_plot.index, df_plot['detected_value_rt'], color='#d62728', lw=2, label='Detection Score')
        ax_score.set_ylabel('Real-Time Detected Score', color = '#d62728')
        ax_score.tick_params(axis = 'y', labelcolor = '#d62728')
        ax_score.set_ylim(-0.1, 1.0)
        for spine in ax.spines.values():
            spine.set_visible(False)
        for spine in ax_score.spines.values():
            spine.set_visible(False)
        ax.grid(False)
        ax_score.grid(False)
        #The thresholding line:
        line_th = ax_score.axhline(y=threshold, color='darkgreen', ls='--', lw=2, alpha=0.8)
        ax_score.axhline(y = threshold, color = 'green', ls = '--', alpha = 0.6)
        soc_match = re.search(r'-(\d+)(SOC|SOC)', filename, re.I)
        soc_str = f"{soc_match.group(1)}% SOC" if soc_match else 'Unknown SOC'
        cell_label = os.path.basename(filename).split('-')
        #title_text = f"Cell: {cell_label} | {soc_str}"
        title_text = "Cell Name Visualization"
        if temp_at_trigger:
            title_text += f"\n The First Singular Value at Trigger: Sigma = {temp_at_trigger:.1f}"
        ax.set_title(title_text, fontweight = 'bold', pad = 25)
        ax.set_label('Time Indice (0.1s)')
        legend_handles = [line_t, line_d]
    fig.legend(legend_handles, ['Signal(First Singular Value)', 'Real-time Detection Score'],
               loc='lower center', ncol=2, bbox_to_anchor=(0.5, 0.02), frameon=True, edgecolor='black')
    #Tight Layout in the Bottom here:
    plt.tight_layout(rect=[0, 0.05, 1, 0.95])
    plt.savefig(output_name, bbox_inches='tight')
    plt.close()
    #plt.show()

#The plots for the NREL dataset: first SVD ~ real-time detected score results:
folder_path = 'SVD_result/SVD_result'
valid_extensions = ('.csv')
if not os.path.exists("NREL_Plots_SVD"):
    os.mkdir("NREL_Plots_SVD")
step_size = 4
list_files = os.listdir(folder_path)
for i in range(0, len(list_files), step_size):
    file_list = list_files[i:(i + step_size)]
    file_list = [folder_path + "/" + file for file in file_list if file != "__MACOSX"]
    plot_battery_quad_SVD(file_list, threshold = 0.3, point_before = 100, point_after = 100,
                      output_name = f'NREL_Plots_SVD/cell{i}_cell{i+step_size}_SVD_result_visualization_NREL.png')

"""## Plot the Simulated dataset:

"""

if not os.path.exists("Simulated_Datasets"):
    os.mkdir("Simulated_Datasets")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
def apply_standard_style():
    """The plots configs"""
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans"],
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 18,
        "ytick.labelsize": 18,
        "legend.fontsize": 18,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "savefig.dpi": 300,
        "figure.constrained_layout.use": True,
        "figure.facecolor": 'white',
        'axes.facecolor': 'white'
    })
apply_standard_style()
file_name = 'Simulated_Datasets/Simulated_Datasets/batteryCCCV_ordinary_54_ws_lower50_merged.csv'
apply_standard_style()
df = pd.read_csv(file_name)
ws_levels = sorted(df['window_size'].unique())
colors = {
    100: "#2166AC",  # blue
    150: "#21908C",  # teal
    200: "#D73027",  # red
    250: "#4575B4",  # steel blue
    300: "#F46D43",  # orange
    350: "#4DAF4A",  # green
    400: "#882E72"   # magenta
}
fig, ax = plt.subplots(figsize = (12, 6))
for ws in ws_levels:
    subset = df[df['window_size'] == ws]
    ax.plot(subset['time_ind'], subset['detected_value_rt'],
            label=f"WS {ws}", color=colors[ws], linewidth=0.75, alpha=0.95)
threshold = 0.3
ax.axhline(y=threshold, color="#B22222", linewidth=2.0, linestyle='--')
ax.text(df['time_ind'].min(), threshold + 0.02, "Threshold 0.3",
        color="#B22222", fontweight="bold", va='bottom', ha='left')
ax.set_xlabel("Time index (0.1 s)")
ax.set_ylabel("Detection score")
ax.set_title("batteryCCCV_ordinary_54 — Detection score by higher window size",
             fontweight='bold',
             pad=8,
             y=1.15)
ax.grid(True, axis='y', linestyle='-', alpha=0.2)
sns.despine()
legend = ax.legend(title="Window size (higher varies)", loc='upper center',
                   bbox_to_anchor=(0.5, 1.15), ncol=4, frameon=False)
plt.setp(legend.get_title(), fontweight='bold')
#Save the picture
if not os.path.exists("Simulated_Datasets_Plots"):
    os.mkdir("Simulated_Datasets_Plots")
output_file = "Simulated_Datasets_Plots/batteryCCCV_ordinary_54_ws_lower50_detection_overlay_py.png"
plt.savefig(output_file, bbox_inches='tight')

def get_slope_calc(df, col_time, col_temp, t_start, t_end):
    """Calculates the slope of temperature over time for a given window."""
    subset = df[(df[col_time] >= t_start) & (df[col_time] <= t_end)]
    if len(subset) < 2:
        return 0.0
    slope, _ = np.polyfit(subset[col_time], subset[col_temp], 1)
    return slope

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from adjustText import adjust_text
#Drawing the slopes here:
def get_window_slope(df, t_start, window_size=10):
    t_end = t_start + window_size
    subset = df[(df['time'] >= t_start) & (df['time'] <= t_end)]
    if len(subset) < 2:
        return 0.0
    slope, _ = np.polyfit(subset['time'], subset['temperature'], 1)
    return slope
def simulate_battery_runaway(duration=150, dt=0.1):
    t = np.arange(0, duration, dt)
    n = len(t)
    t_abuse_start = 5
    t_tr_start = 12.5
    temp = np.zeros(n)
    for i, time in enumerate(t):
        if time < t_abuse_start:
            temp[i] = 25 + np.random.normal(0, 0.5)
        elif time < t_tr_start:
            temp[i] = 25 + 0.75 * (time - t_abuse_start) + np.random.normal(0, 1.5)
        else:
            growth = 10 * np.exp(0.5 * (time - t_tr_start))
            temp[i] = min(800, temp[i-1] + growth) + np.random.normal(0, 1.25)
    voltage = np.zeros(n)
    for i, time in enumerate(t):
        if time < t_tr_start:
            voltage[i] = 4.2 - 0.0005 * time + np.random.normal(0, 0.1)
        else:
            voltage[i] = max(0, 4.15 * np.exp(-0.8 * (time - t_tr_start))) + np.random.normal(0, 0.05)
    force = np.zeros(n)
    for i, time in enumerate(t):
        if time < t_abuse_start:
            force[i] = 50 + np.random.normal(0, 3)
        elif time < t_tr_start:
            force[i] = 50 + 3 * (time - t_abuse_start) + np.random.normal(0, 3.5)
        else:
            peak = 1500 * np.exp(-0.3 * (time - t_tr_start)) * np.abs(np.sin(0.2*(time-t_tr_start)))
            force[i] = 200 + peak + np.random.normal(0, 10)
    return pd.DataFrame({
        'time': t,
        'temperature': temp,
        'voltage': voltage,
        'force': force
    })


def plot_simulated_panel(ax_temp, df_sim):
    l1, = ax_temp.plot(df_sim['time'], df_sim['temperature'],
                       color='#d62728', lw=3, label='Temperature')
    ax_temp.set_ylabel('Temperature (°C)', color='#d62728',
                       fontweight='bold', fontsize=18)
    ax_temp.tick_params(axis='y', labelcolor='#d62728', labelsize=18)
    ax_force = ax_temp.twinx()
    ax_force.spines.right.set_position(("axes", 1.0))
    l2, = ax_force.plot(df_sim['time'], df_sim['force'],
                        color='#2ca02c', lw=2, alpha=0.7)
    ax_force.set_ylabel('Force (N)', color='#2ca02c',
                        fontweight='bold', fontsize=18)
    ax_force.tick_params(axis='y', labelcolor='#2ca02c', labelsize=18)
    ax_volt = ax_temp.twinx()
    ax_volt.spines.right.set_position(("axes", 1.12))
    l3, = ax_volt.plot(df_sim['time'], df_sim['voltage'],
                       color='darkblue', lw=2, alpha=0.7)
    ax_volt.set_ylabel('Voltage (V)', color='darkblue',
                       fontweight='bold', fontsize=18)
    ax_volt.tick_params(axis='y', labelcolor='darkblue', labelsize=18)
    ax_temp.axvspan(0, 5, color='gray', alpha=0.1)
    ax_temp.text(3, 920, 'Stage 1:\nStable',
                 ha='center', fontweight='bold', fontsize=18)
    ax_temp.axvspan(5, 12.5, color='orange', alpha=0.1)
    ax_temp.text(8.5, 920, 'Stage 2:\nAbuse/Heating',
                 ha='center', fontweight='bold', fontsize=18)
    ax_temp.axvspan(12.5, 20, color='red', alpha=0.1)
    ax_temp.text(16, 920, 'Stage 3:\nThermal Runaway',
                 ha='center', fontweight='bold', fontsize=18)
    win_size = 0.25
    test_points = [3, 13]
    for tp in test_points:
        slope = get_window_slope(df_sim, tp, win_size)
        ax_temp.axvspan(tp, tp + win_size, color='blue', alpha=0.15)
        y_val = df_sim.loc[np.isclose(df_sim['time'], tp), 'temperature'].values[0]
        ax_temp.annotate(
            f'Window Slope:\n{slope:.2f} °C/s',
            xy=(tp + win_size/2, y_val),
            xytext=(tp + 2.25, y_val + 90),
            arrowprops=dict(facecolor='black', shrink=0.1, width=2.25, headwidth=10),
            fontsize=16, fontweight='bold',
            bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="blue", alpha=0.8)
        )
    ax_temp.set_title("Battery Thermal Runaway: Running Window Slope Analysis",
                      fontweight='bold', pad=44, fontsize=25)
    ax_temp.set_xlim(0, 20)
    ax_temp.set_ylim(0, 910)
    return ax_force, ax_volt


def plot_minimal_pro_T_panel(ax, filename, threshold=0.3, point_before=100, point_after=100):
    df = pd.read_csv(filename)
    trigger_indices = df.index[df['detected_value_rt'] >= threshold].tolist()
    if trigger_indices:
        trigger_point = trigger_indices[0]
        start_idx = max(0, trigger_point - point_before)
        end_idx = min(len(df), trigger_point + point_after)
        df_plot = df.iloc[start_idx:end_idx].reset_index(drop=True)
        val = df.iloc[trigger_point]['temperature']
        temp_at_trigger = float(val.iloc if hasattr(val, 'iloc') else val)
    else:
        df_plot = df.iloc[:min(len(df), 1500)].reset_index(drop=True)
        temp_at_trigger = None
    time_seconds = df_plot.index * 0.1
    ax.plot(time_seconds, df_plot['temperature'], color='#d62728', lw=3.5)
    ax.set_ylabel('Temperature (°C)', color='#d62728',
                  fontsize=20, fontweight='bold')
    ax.tick_params(axis='y', labelcolor='#d62728', labelsize=20, length=4)
    ax_score = ax.twinx()
    ax_score.plot(time_seconds, df_plot['detected_value_rt'],
                  color='darkblue', lw=3.5)
    ax_score.axhline(y=threshold, color='green', ls='--', alpha=0.5)
    ax_score.set_ylim(-0.1, 1.1)
    ax_score.set_ylabel('Detected Score', color='darkblue',
                        fontsize=18, fontweight='bold')
    ax_score.tick_params(axis='y', labelcolor='darkblue', labelsize=20, length=4)
    for spine in ax.spines.values():
        spine.set_visible(False)
    for spine in ax_score.spines.values():
        spine.set_visible(False)
    ax.grid(False)
    ax_score.grid(False)
    title_text = "Battery Cell Thermal Analysis"
    if temp_at_trigger is not None:
        title_text += f" | Temp at Trigger: {temp_at_trigger:.1f}°C"
    ax.set_title(title_text, fontsize=24, fontweight='bold', pad=25)
    return ax_score

def plot_combined_shared_x(
    rt_filename,
    threshold=0.3,
    point_before=100,
    point_after=100,
    output_name='combined_shared_x_plot.png'
):
    df_sim = simulate_battery_runaway(duration=20, dt=0.1)
    fig, (ax1, ax2) = plt.subplots(
        2, 1,
        figsize=(14, 16),
        sharex=True,
        gridspec_kw={'hspace': 0.12}
    )
    ax1_force, ax1_volt = plot_simulated_panel(ax1, df_sim)
    ax2_score = plot_minimal_pro_T_panel(
        ax2,
        rt_filename,
        threshold=threshold,
        point_before=point_before,
        point_after=point_after
    )
    ax2.set_xlabel('Time (Seconds)', fontsize=20, fontweight='bold')
    ax2.set_xlim(0, 20)
    fig.subplots_adjust(top=0.93)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.savefig(output_name, dpi=300, bbox_inches='tight')
    plt.show()
    plt.close()
    print(f"Combined figure saved: {output_name}")
plot_combined_shared_x(
    rt_filename='T_Results/T_Results/Sorteria-Control-60SOC-cell1.xlsx_reform_severity_level7.csv_rt_detect_result_window100.csv',
    threshold=0.3,
    point_before=100,
    point_after=100,
    output_name='Simulated_Datasets_Plots/pTRPred_Visualization_Diagram.png'
)

import pandas as pd
import matplotlib.pyplot as plt
currents =[27, 54, 81, 108, 135]
files = [f"df_t_batterycccv{c}.csv" for c in currents]
THRESHOLD = 0.3
plt.rcParams.update({'font.family': 'sans-serif', 'figure.facecolor': 'white'})
LABEL_SIZE, TICK_SIZE, TITLE_SIZE = 20, 18, 20
fig, axes = plt.subplots(3, 2, figsize=(18, 20))
axes = axes.flatten()
fig.delaxes(axes[5])
pos4 = axes[4].get_position()
pos5 = axes[5].get_position()
middle_x = (pos4.x0 + pos5.x0) / 2.5
axes[4].set_position([middle_x, pos4.y0, pos4.width, pos4.height])
handles = []
for i, (amp, fname) in enumerate(zip(currents, files)):
    ax1 = axes[i]
    df = pd.read_csv("Simulated_Datasets/Simulated_Datasets/" + fname)
    df['temp_C'] = df['signal'] - 273.15 #Transform from F to C
    l1, = ax1.plot(df['time_ind'], df['temp_C'], color='#d62728', lw=2.0)
    ax1.set_ylabel('Temp (°C)', color='#d62728', fontweight='bold', fontsize=LABEL_SIZE)
    ax1.set_xlabel('Time Index (0.1s)', fontweight='bold', fontsize=LABEL_SIZE)
    ax1.tick_params(axis='both', labelsize=TICK_SIZE)
    ax1.tick_params(axis='y', labelcolor='#d62728')
    ax1.grid(True, linestyle='--', alpha=0.3)
    # 2. Right Axis: Real-time Detection Score
    ax2 = ax1.twinx()
    l2, = ax2.plot(df['time_ind'], df['detected_value_rt'], color='darkblue', lw=2.0)
    ax2.set_ylabel('Detection Score', color='darkblue', fontweight='bold', fontsize=LABEL_SIZE)
    ax2.tick_params(axis='y', labelcolor='darkblue', labelsize=TICK_SIZE)
    ax2.set_ylim(-0.1, 1.1)
    # 3. Thresholding Line
    l3 = ax2.axhline(y=THRESHOLD, color='darkgreen', linestyle='--', lw=2.0)
    ax1.set_title(f"Sensitivity Analysis, Charging Cycle: Current {amp} A", fontsize=TITLE_SIZE, fontweight='bold')
    if i == 0:
        handles = [l1, l2, l3]
plt.tight_layout(rect=[0, 0.08, 1, 0.95])
# Adding the legend
fig.legend(handles, ['Temperature (°C)', 'Detection Score', f'Threshold ({THRESHOLD})'],
           loc='lower center', ncol=3, bbox_to_anchor=(0.5, 0.03),
           frameon=True, edgecolor='black', shadow=True, fontsize=20)
plt.savefig("Simulated_Datasets_Plots/Battery_MultiCurrent_3by2.png", dpi=300)
plt.show()

def apply_standard_style():
    """The plots configs"""
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans"],
        "axes.titlesize": 20,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 18,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "savefig.dpi": 300,
        "figure.constrained_layout.use": True,
        "figure.facecolor": 'white',
        'axes.facecolor': 'white'
    })

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('Simulated_Datasets/Simulated_Datasets/dataset_description_with_time3.csv')
data = pd.to_numeric(df["second_buy"], errors='coerce').dropna()
data = data[(data >= 0) & (data <= 80)]
fig, ax = plt.subplots(figsize=(10, 6), facecolor="white")
bins = np.arange(0, 101, 10)
ax.hist(data, bins=bins, color='darkblue', edgecolor="white", linewidth=1.2, alpha=0.85, zorder=3)
mean_val, median_val = data.mean(), data.median()
ax.axvline(mean_val, color='#d62728', linestyle="--", linewidth=2.25, label=f"Mean: {mean_val:.1f}s", zorder=4)
ax.axvline(median_val, color="#F5A623", linestyle="-", linewidth=2.25, label=f"Median: {median_val:.1f}s", zorder=4)
#ax.set_title(f"Lead Time Distribution", pad=20, fontweight='bold', fontsize = 20)
ax.set_xlabel("Lead Time(seconds)", labelpad=10, fontsize = 16)
ax.set_ylabel("Number of Cells", labelpad=10, fontsize = 16)
ax.set_xlim(0, 100)
ax.set_xticks(bins)
#ax.grid(axis='y', linestyle=':', alpha=0.7, zorder=0)
for s in ['top', 'right']: ax.spines[s].set_visible(False)
ax.legend(loc="upper right", fontsize = 18)
ax.grid(False)
plt.tight_layout(rect=[0, 0.08, 1, 0.95])
plt.tight_layout()
plt.savefig('Simulated_Datasets_Plots/Lead_Time_Distribution.png')
plt.show()



"""## Mean Loading Proportion Visualizations:

"""

import requests
import os
from google.colab import userdata

#Drawing the plots across different positions:
from google.colab import userdata
token = userdata.get("GITHUB_TOKEN")

url = "https://raw.githubusercontent.com/ruanhq-StatsML/pTRpred_Heqiao/main/Reproducible_Plots/loading_proportions.zip"

!curl -L \
  -H "Authorization: token {token}" \
  -H "Accept: application/vnd.github.raw" \
  "{url}" \
  -o "loading_proportions.zip"
!unzip -o loading_proportions.zip -d loading_proportions

os.remove('100_30_Loading_Contribution.zip')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def apply_standard_style():
    """The plots configs"""
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans"],
        "axes.titlesize": 21,
        "axes.labelsize": 18,
        "xtick.labelsize": 18,
        "ytick.labelsize": 18,
        "legend.fontsize": 18,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "savefig.dpi": 300,
        "figure.constrained_layout.use": True,
        "figure.facecolor": 'white',
        'axes.facecolor': 'white'
    })

apply_standard_style()
def plot_individual_plot(csv_path, point_trigger_path, output_name):
    df = pd.read_csv(csv_path)
    dataset_name = csv_path.split('/')[-1].split('_')[0][:-7]
    df_name_point_trigger = pd.read_csv(point_trigger_path)
    trigger_point = df_name_point_trigger.loc[df_name_point_trigger['dataset_name'] == dataset_name, 'window_index']
    if len(trigger_point) == 0:
        return
    trigger_point = trigger_point.iloc[0]
    start_ind = trigger_point - 10
    end_ind = trigger_point + 10
    df_sub = df[(df['Window_Index'] >= trigger_point - 10) & (df['Window_Index'] <= trigger_point + 10)].copy()
    cols = ['Loading_Temperature_Prop', 'Loading_force_Prop', 'Loading_Voltage_Prop']
    labels = ['Temperature', 'Force', 'Voltage']
    colors = ['#d62728', '#1f77b4', '#2ca02c']
    means = []
    fig, ax1 = plt.subplots(figsize=(12, 8), dpi=100)
    for col, label, color in zip(cols, labels, colors):
        y_data = df_sub[col].values
        x_data = df_sub['Window_Index'].values
        ax1.plot(x_data, y_data, label=label, color=color, linewidth=2.5, zorder=3)
        m_val = float(np.mean(y_data))
        means.append(m_val)
        ax1.axhline(y=m_val, color=color, linestyle=':', alpha=0.4, linewidth=1)
    ax1.set_yscale('log')
    all_values = df_sub[cols].values.flatten()
    ymin = max(all_values[all_values > 0].min() * 0.5, 1e-4)
    ymax = min(all_values.max() * 2, 1.2)
    ax1.set_ylim(ymin, ymax)
    ax1.axvline(x=trigger_point, color='red', linestyle='--', linewidth=2, alpha=0.8,
                label=f'Detected TR ({trigger_point})', zorder=4)
    ax2 = ax1.twinx()
    ax2.set_yscale('log')
    ax2.set_ylim(ax1.get_ylim())
    ax2.set_yticks(means)
    ax2.set_yticklabels([f'{m:.3f}' for m in means])
    ax2.spines['right'].set_visible(False)
    ax2.spines['top'].set_visible(False)
    for i, tick in enumerate(ax2.get_yticklabels()):
        tick.set_color(colors[i])
        tick.set_fontweight('bold')
        tick.set_fontsize(15)
    ax1.set_title(f'Loading Analysis | {dataset_name}\nLog Scale, Window indexes {max(start_ind, 0)}-{end_ind}', fontweight='bold', pad=15)
    ax1.set_xlabel('Window Index')
    ax1.set_ylabel('Loading Proportion (Log)')
    ax1.set_xlim(start_ind, end_ind)
    ax1.grid(True, which="both", linestyle='--', alpha=0.15, zorder=0)
    ax1.legend(loc='lower right', frameon=True, framealpha=0.8)
    plt.tight_layout()
    plt.savefig(output_name, bbox_inches='tight')

folder_path = 'loading_proportions/100_30'
valid_extensions = '100_30.csv'
list_files = [p for p in os.listdir(folder_path) if p.endswith(valid_extensions)]
point_trigger_path = 'loading_proportions/100_30/detection_point_trigger.csv'
for f in list_files:
    file_path = os.path.join(folder_path, f)
    dataset_name = file_path.split('/')[-1].split('_')[0][:-7]
    print(f"Processing: {dataset_name}")
    output_df = f'loading_proportion_plot/{dataset_name}_loading_prop.png'
    plot_individual_plot(csv_path = file_path, point_trigger_path = point_trigger_path,
                         output_name = output_df)

rm -rf loading_proportion_plot/*

"""## Zip the resulting folders and save back to Github:
### [1] NREL_Plots: Plots for the Temperature ~ Real-Time Detected Score Visualizations - on Temperature Individual Dimension
### [2] NREL_Plots: Plots for the First Singular Value ~ Real-Time Detected Score Visualizations - SVD Procedure
### [3] Simulated_Datasets_Plots: The results on the simulated data, include the visualization digram.
### [4] Threshold_Sensitivity: Threshold Sensitivity Plot for Temperature Based Procedure and the SVD Based Procedure
### [5] Loading Proportion Visualizations:
#### The output files include: "Simulated_Datasets_Plots_backgithub.zip", "Threshold_Sensitivity_backgithub.zip", "NREL_Plots_SVD_backgithub.zip", "NREL_Plots_backgithub.zip", "loading_proportion_plot.zip"
"""

import shutil

shutil.make_archive('loading_proportion_plot_backgithub', 'zip', 'loading_proportion_plot')

shutil.make_archive('Simulated_Datasets_Plots_backgithub', 'zip', 'Simulated_Datasets_Plots')

shutil.make_archive('Threshold_Sensitivity_backgithub', 'zip', 'Threshold_Sensitivity')

shutil.make_archive('NREL_Plots_SVD_backgithub', 'zip', 'NREL_Plots_SVD')

shutil.make_archive('NREL_Plots_backgithub', 'zip', 'NREL_Plots')

#Mount to google drive.
!cp /content/NREL_Plots_backgithub.zip /content/drive/MyDrive/
!cp /content/NREL_Plots_SVD_backgithub.zip /content/drive/MyDrive/
!cp /content/Threshold_Sensitivity_backgithub.zip /content/drive/MyDrive/
!cp /content/Simulated_Datasets_Plots_backgithub.zip /content/drive/MyDrive/
!cp /content/loading_proportion_plot_backgithub.zip /content/drive/MyDrive/